# Config for Image-Only Attention Classifier
model_type: "image_only"
device: "cuda"

data:
  csv_path: "/home/won_ju_kim/yhchoi/PSG_260408/final_combined_data.csv"
  patient_id_col: "ID"
  labels:
    - "adherence_3m"
    - "adherence_6m"
    - "adherence_9m"
    - "adherence_1yr"
    - "adherence_2yr"
    - "adherence_3yr"
    - "adherence_4yr"
    - "adherence_5yr"
  condition_ons: null

training:
  epochs: 500
  patience: 30
  lr: 0.0001
  batch_size: 32
  model_save_dir: "/home/won_ju_kim/yhchoi/PSG_260408/pfn_exp_pt_260521/image_only"
  log_save_path: "/home/won_ju_kim/yhchoi/PSG_260408/pfn_exp_pt_260521/image_only/logs/results.csv"
  k_folds: 5

model:
  embed_dim: 128
  num_heads: 8
